package driver

type VariableDef struct {
	Key      string
	Type     string
	Unit     string
	Readable bool
	Writable bool
}

var variableDefinitions = []VariableDef{
	{Key: "GasSensorStatus", Type: "Boolean", Readable: true, Writable: false},
	{Key: "GasAlarmMode", Type: "Text", Readable: true, Writable: true},
	{Key: "CoLimitOfGasSensor", Type: "Number", Unit: "ppm", Readable: true, Writable: true},
	{Key: "SoftNetworkReset", Type: "Boolean", Readable: true, Writable: true},
	{Key: "OnlineNetworkReset", Type: "Boolean", Readable: true, Writable: true},
	{Key: "OnlineReset", Type: "Boolean", Readable: true, Writable: true},
	{Key: "OnlineFactoryReset", Type: "Boolean", Readable: true, Writable: true},
	{Key: "ResetHoldTime", Type: "Number", Unit: "ms", Readable: true, Writable: true},
	{Key: "AllEvents", Type: "Text", Readable: true, Writable: false},
	{Key: "ManageEvents", Type: "Text", Readable: true, Writable: true},
	{Key: "availableSubsEvents", Type: "Text", Readable: true, Writable: false},
	{Key: "eventSubscribtion", Type: "Text", Readable: true, Writable: true},
	{Key: "5VBuzzer1Status", Type: "Boolean", Readable: true, Writable: true},
	{Key: "SNMP_Enable", Type: "Boolean", Readable: true, Writable: true},
	{Key: "SNMPStatus", Type: "Boolean", Readable: true, Writable: false},
	{Key: "Communityname", Type: "Text", Readable: true, Writable: true},
	{Key: "MQTT_Enable", Type: "Boolean", Readable: true, Writable: true},
	{Key: "MQTT_password", Type: "Password", Readable: true, Writable: true},
	{Key: "MQTT_username", Type: "Text", Readable: true, Writable: true},
	{Key: "MQTT_Topic", Type: "Text", Readable: true, Writable: true},
	{Key: "deviceSubType_ID", Type: "Text", Readable: true, Writable: false},
	{Key: "username", Type: "Text", Readable: true, Writable: true},
	{Key: "Type", Type: "Text", Readable: true, Writable: false},
	{Key: "Category", Type: "Text", Readable: true, Writable: false},
	{Key: "Manufacturer", Type: "Text", Readable: true, Writable: false},
	{Key: "UUID", Type: "Text", Readable: true, Writable: false},
	{Key: "ModelName", Type: "Text", Readable: true, Writable: false},
	{Key: "FirmwareVersion", Type: "Text", Readable: true, Writable: false},
	{Key: "DeviceName", Type: "Text", Readable: true, Writable: true},
	{Key: "Restarts", Type: "Number", Readable: true, Writable: false},
	{Key: "RunningTime", Type: "Text", Readable: true, Writable: false},
	{Key: "SSID", Type: "Text", Readable: true, Writable: true},
	{Key: "DNS", Type: "Text", Readable: true, Writable: true},
	{Key: "DHCP", Type: "Boolean", Readable: true, Writable: true},
	{Key: "subNet", Type: "Text", Readable: true, Writable: true},
	{Key: "SignalStrengthIndicator", Type: "Number", Unit: "dBm", Readable: true, Writable: false},
	{Key: "IPAddress", Type: "Text", Readable: true, Writable: true},
	{Key: "GatewayIP", Type: "Text", Readable: true, Writable: true},
	{Key: "MACAddress", Type: "Text", Readable: true, Writable: false},
	{Key: "NTPServer", Type: "Text", Readable: true, Writable: true},
	{Key: "TimeZone", Type: "Text", Readable: true, Writable: true},
	{Key: "TimeMode", Type: "Text", Readable: true, Writable: true},
	{Key: "Date", Type: "Text", Readable: true, Writable: true},
	{Key: "Time", Type: "Text", Readable: true, Writable: true},
	{Key: "IrTransmitter2", Type: "Text", Readable: true, Writable: true},
	{Key: "IrTransmitter1", Type: "Text", Readable: true, Writable: true},
	{Key: "Relay2OffTime", Type: "Text", Readable: true, Writable: true},
	{Key: "Relay2OnTime", Type: "Text", Readable: true, Writable: true},
	{Key: "Relay2Status", Type: "Boolean", Readable: true, Writable: true},
	{Key: "Relay1OffTime", Type: "Text", Readable: true, Writable: true},
	{Key: "Relay1OnTime", Type: "Text", Readable: true, Writable: true},
	{Key: "Relay1Status", Type: "Boolean", Readable: true, Writable: true},
	{Key: "Contact2CloseTime", Type: "Text", Readable: true, Writable: false},
	{Key: "Contact2OpenTime", Type: "Text", Readable: true, Writable: false},
	{Key: "Contact2", Type: "Boolean", Readable: true, Writable: false},
	{Key: "Contact1CloseTime", Type: "Text", Readable: true, Writable: false},
	{Key: "Contact1OpenTime", Type: "Text", Readable: true, Writable: false},
	{Key: "Contact1", Type: "Boolean", Readable: true, Writable: false},
	{Key: "HumiditySensor1", Type: "Number", Unit: "%", Readable: true, Writable: false},
	{Key: "OffSetOfHumiditySensor1", Type: "Number", Unit: "%", Readable: true, Writable: true},
	{Key: "TemperatureSensor1", Type: "Number", Unit: "°C", Readable: true, Writable: false},
	{Key: "OffSetOfTemperatureSensor1", Type: "Number", Unit: "°C", Readable: true, Writable: true},
	{Key: "GasSensor", Type: "Number", Unit: "ppm", Readable: true, Writable: false},
}
