BIN_DIR=bin
BIN_NAME=driver
DRIVER_ID=com.notrix.camera.isapi
VERSION=0.1.0
PACKAGER=../../../nx-driver-packager/nx-driver-packager.exe
OUTPUT_DIR=../../../controller-platform/_tmp

.PHONY: build
build:
	mkdir -p $(BIN_DIR)
	go build -o $(BIN_DIR)/$(BIN_NAME) ./cmd/driver

.PHONY: build-linux
build-linux:
	mkdir -p $(BIN_DIR)
	GOOS=linux GOARCH=amd64 go build -o $(BIN_DIR)/$(BIN_NAME) ./cmd/driver

.PHONY: package-linux
package-linux: build-linux
	$(PACKAGER) pack --input . --out $(OUTPUT_DIR)/$(DRIVER_ID)-$(VERSION)-linux-amd64.nxpkg

.PHONY: package
package: build
	tar -czf driver-package.tgz manifest.json config.schema.json endpoints.json variables.schema.json capabilities.json events.json -C $(BIN_DIR) $(BIN_NAME)

.PHONY: clean
clean:
	rm -rf $(BIN_DIR) driver-package.tgz
